[profile.default]
solc = "0.8.28"
solc_version = "0.8.28"
src = 'src'
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./out"}, {access = "read", path = "./test/bin"}]
verbosity = 3
evm_version = "cancun"
gas_limit = "300000000"
bytecode_hash = "none"
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
auto_detect_solc = true

libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

rpc_endpoints = { sepolia = "${SEPOLIA_RPC_URL}" }
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100